### ISSUE TITLE
request: add restricted roles for role and announcement 

### ISSUE THREAD

**Issue by Swiizyy** [BirthdayyBot/BirthdayyBot#582]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

This feature allows you to add a restriction at the module level for certain roles.

### Desired solution

Ads will only be restricted for the `@MUTED` role:
```
Announcement Restricted Mode: PROHIBITED
Announcement Restricted Role: `@MUTED`
```

Ads will only be authorized for the `@MEMBER` role:
```
Announcement Restricted Mode: AUTHORISED
Announcement Restricted Role: `@MEMBER`
```

By default, ads will be allowed for all roles.

### Alternatives considered

I don't see an alternative

**Comment by nikolaischunk** [comment]
As commented in the PR:

If understood this change request correctly, it wants to enable/disable certain roles to make changes to the configuration of specific settings.

I don't think that it is necessary to add this feature due to the following reasons:

This introduces changes that make birthdayy more complex to use and understand & this can mostly already be achieved by discords internal tool, that allows server admins to customize the access to the /config set command.

There is little need to extra allow access to a specific setting, also because the settings usually are not changing, once their set.

**Comment by Swiizyy** [comment]
> As commented in the PR:
> 
> If understood this change request correctly, it wants to enable/disable certain roles to make changes to the configuration of specific settings.
> 
> I don't think that it is necessary to add this feature due to the following reasons:
> 
> This introduces changes that make birthdayy more complex to use and understand & this can mostly already be achieved by discords internal tool, that allows server admins to customize the access to the /config set command.
> 
> There is little need to extra allow access to a specific setting, also because the settings usually are not changing, once their set.

No you misunderstood it doesn't change the parameters but the behavior at the reminder level.

**Comment by nikolaischunk** [comment]
can our explain the flow that you are
imagining? A new command? If not, I really didn't understand what you mean exactly😅
